In [5]:
import pandas as pd

In [1]:
from sklearn.preprocessing import LabelEncoder

In [6]:
path = "/content/restaurant_tips_dataset-Tips Data.csv"

In [7]:
df = pd.read_csv(path)

In [8]:
df.head()

  Total Bill ($) Tip ($)  Tip %     Sex Smoker   Day    Time  Party Size
0         $22.54   $4.66  20.7%  Female     No   Fri  Dinner         2.0
1         $27.64   $4.43  16.0%    Male    Yes   Sun  Dinner         2.0
2         $34.24   $4.13  12.1%  Female    Yes   Sat  Dinner         2.0
3         $47.97   $8.56  17.8%    Male     No   Sat  Dinner         4.0
4         $26.18   $4.40  16.8%    Male     No  Thur   Lunch         2.0

In [2]:
label = LabelEncoder()

In [9]:
df['Sex'] = label.fit_transform(df['Sex'])

In [10]:
df.head()

  Total Bill ($) Tip ($)  Tip %  Sex Smoker   Day    Time  Party Size
0         $22.54   $4.66  20.7%    0     No   Fri  Dinner         2.0
1         $27.64   $4.43  16.0%    1    Yes   Sun  Dinner         2.0
2         $34.24   $4.13  12.1%    0    Yes   Sat  Dinner         2.0
3         $47.97   $8.56  17.8%    1     No   Sat  Dinner         4.0
4         $26.18   $4.40  16.8%    1     No  Thur   Lunch         2.0

In [12]:
df['Smoker'] = label.fit_transform(df['Smoker'])

In [13]:
df.head()

  Total Bill ($) Tip ($)  Tip %  Sex  Smoker   Day    Time  Party Size
0         $22.54   $4.66  20.7%    0       0   Fri  Dinner         2.0
1         $27.64   $4.43  16.0%    1       1   Sun  Dinner         2.0
2         $34.24   $4.13  12.1%    0       1   Sat  Dinner         2.0
3         $47.97   $8.56  17.8%    1       0   Sat  Dinner         4.0
4         $26.18   $4.40  16.8%    1       0  Thur   Lunch         2.0

In [14]:
df.Day.unique()

array(['Fri', 'Sun', 'Sat', 'Thur', nan], dtype=object)

In [15]:
df.Day = label.fit_transform(df.Day)

In [16]:
df.head()

  Total Bill ($) Tip ($)  Tip %  Sex  Smoker  Day    Time  Party Size
0         $22.54   $4.66  20.7%    0       0    0  Dinner         2.0
1         $27.64   $4.43  16.0%    1       1    2  Dinner         2.0
2         $34.24   $4.13  12.1%    0       1    1  Dinner         2.0
3         $47.97   $8.56  17.8%    1       0    1  Dinner         4.0
4         $26.18   $4.40  16.8%    1       0    3   Lunch         2.0