In [42]:
import pandas as pd

In [43]:
path = "/content/twitter_dataset.csv"

In [66]:
df = pd.read_csv(path)

In [67]:
df.head()

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,Party least receive say or single. Prevent pre...,2,25,2023-01-30 11:00:51
1,2,richardhester,Hotel still Congress may member staff. Media d...,35,29,2023-01-02 22:45:58
2,3,williamsjoseph,Nice be her debate industry that year. Film wh...,51,25,2023-01-18 11:25:19
3,4,danielsmary,Laugh explain situation career occur serious. ...,37,18,2023-04-10 22:06:29
4,5,carlwarren,Involve sense former often approach government...,27,80,2023-01-24 07:12:21

In [68]:
df.shape

(10000, 6)

In [47]:
df = df.head(300)

In [48]:
df['Text'] = df['Text'].str.lower()

In [49]:
df.head(300)

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,party least receive say or single. prevent pre...,2,25,2023-01-30 11:00:51
1,2,richardhester,hotel still congress may member staff. media d...,35,29,2023-01-02 22:45:58
2,3,williamsjoseph,nice be her debate industry that year. film wh...,51,25,2023-01-18 11:25:19
3,4,danielsmary,laugh explain situation career occur serious. ...,37,18,2023-04-10 22:06:29
4,5,carlwarren,involve sense former often approach government...,27,80,2023-01-24 07:12:21
...,...,...,...,...,...,...
295,296,phenderson,community best evening evidence work who full ...,96,95,2023-04-21 18:36:52
296,297,amy24,tell reveal director member sea game important...,90,100,2023-04-10 23:24:13
297,298,emedina,peace none for prevent picture fire program in...,74,25,2023-04-15 23:14:10
298,299,bergervanessa,tv mouth sort. rest too southern a half school...,80,1,2023-02-22 03:12:55
299,300,barrettchristopher,so never book station action value. try north ...,85,19,2023-01-09 19:39:19

In [69]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [70]:
df['Text'] = df['Text'].apply(remove_punctuation)

In [71]:
df.head()

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,Party least receive say or single Prevent prev...,2,25,2023-01-30 11:00:51
1,2,richardhester,Hotel still Congress may member staff Media dr...,35,29,2023-01-02 22:45:58
2,3,williamsjoseph,Nice be her debate industry that year Film whe...,51,25,2023-01-18 11:25:19
3,4,danielsmary,Laugh explain situation career occur serious F...,37,18,2023-04-10 22:06:29
4,5,carlwarren,Involve sense former often approach government...,27,80,2023-01-24 07:12:21

In [72]:
from textblob import TextBlob

def correct_spelling(text):
    return str(TextBlob(text).correct())

In [74]:
df['Text'] = df['Text'].apply(correct_spelling)

In [75]:
df.head()

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,Party least receive say or single Prevent prev...,2,25,2023-01-30 11:00:51
1,2,richardhester,Hotel still Congress may member staff Media dr...,35,29,2023-01-02 22:45:58
2,3,williamsjoseph,Vice be her debate industry that year Film whe...,51,25,2023-01-18 11:25:19
3,4,danielsmary,Laugh explain situation career occur serious G...,37,18,2023-04-10 22:06:29
4,5,carlwarren,Involve sense former often approach government...,27,80,2023-01-24 07:12:21

In [76]:
from nltk.tokenize import word_tokenize

In [77]:
import nltk

In [78]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [79]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [80]:
df['Text'] = df['Text'].apply(word_tokenize)

In [81]:
df

,Tweet_ID,Username,Text,Retweets,Likes,Timestamp
0,1,julie81,"[Party, least, receive, say, or, single, Preve...",2,25,2023-01-30 11:00:51
1,2,richardhester,"[Hotel, still, Congress, may, member, staff, M...",35,29,2023-01-02 22:45:58
2,3,williamsjoseph,"[Vice, be, her, debate, industry, that, year, ...",51,25,2023-01-18 11:25:19
3,4,danielsmary,"[Laugh, explain, situation, career, occur, ser...",37,18,2023-04-10 22:06:29
4,5,carlwarren,"[Involve, sense, former, often, approach, gove...",27,80,2023-01-24 07:12:21
...,...,...,...,...,...,...
9995,9996,ntate,"[Agree, reflect, military, box, ability, ever,...",81,86,2023-01-15 11:46:20
9996,9997,garrisonjoshua,"[Worn, which, push, still, Degree, sometimes, ...",73,100,2023-05-06 00:46:54
9997,9998,adriennejackson,"[You, day, agent, likely, region, Teacher, dat...",10,62,2023-02-27 14:55:08
9998,9999,kcarlson,"[Guess, without, successful, save, Articular, ...",21,60,2023-01-09 16:09:35
9999,10000,vdickerson,"[Body, onto, understand, team, about, product,...",65,54,2023-04-19 01:35:56

In [85]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def remove_stopwords(words):
    return [word for word in words if word.lower() not in stop_words]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [88]:
df['Text'] = df['Text'].apply(remove_stopwords)

In [89]:
from nltk.stem import PorterStemmer

In [90]:
stemmer = PorterStemmer()

def stem_words(words):
    return [stemmer.stem(word) for word in words]

In [91]:
df['Text'] = df['Text'].apply(stem_words)