In [ ]:
import pandas as pd

In [27]:
path = "/content/messy_text.csv"

In [59]:
df = pd.read_csv(path, on_bad_lines='skip')

In [29]:
df = df.head(100)

In [60]:
df.head()

,text,html_content,url,abbreviation_text
0,Hello WORLD!!!,<p>Hello WORLD!!!</p>,https://example.com/test?x=1&y=2,"BTW, this is GREAT!!!"
1,THIS is lowercase-ish...,<div><strong>THIS</strong> is lowercase-ish......,http://www.example.org/page,FYI: check this ASAP!
2,wow... REALLY???,<h1>wow... REALLY???</h1>,https://openai.com/,LOL!!! idk why :)
3,Mixed CaSe TeXt,<span>Mixed CaSe TeXt</span>,https://example.com/a/b#section,"IMO, it's OK."
4,extra spaces,<p> extra spaces </p>,www.example.com,pls fix this... thx!

In [61]:
columns = ['text', 'html_content', 'url','abbreviation_text']

**To Lowercase**

In [62]:
df[columns] = df[columns].apply(lambda x: x.str.lower())

In [63]:
df[columns]

,text,html_content,url,abbreviation_text
0,hello world!!!,<p>hello world!!!</p>,https://example.com/test?x=1&y=2,"btw, this is great!!!"
1,this is lowercase-ish...,<div><strong>this</strong> is lowercase-ish......,http://www.example.org/page,fyi: check this asap!
2,wow... really???,<h1>wow... really???</h1>,https://openai.com/,lol!!! idk why :)
3,mixed case text,<span>mixed case text</span>,https://example.com/a/b#section,"imo, it's ok."
4,extra spaces,<p> extra spaces </p>,www.example.com,pls fix this... thx!
...,...,...,...,...
95,this is a test sentence with mixed case....,<ul><li>this is a test sentence with mixed cas...,https://www.google.com/search?q=hello%20world,lol... what happened???
96,this is a test sentence with mixed case.!!!???,"<a href=""https://example.com/products/item-42?...",https://example.com/products/item-42?ref=email...,btw... did you see this?
97,please review this asap... thanks! --,<ul><li>please review this asap... thanks! -- ...,https://openai.com/research/,til something new!!!
98,"normal text here, but not too normal......","<strong>normal text here, but not too normal.....",https://www.google.com/search?q=hello%20world,"idk, maybe it's fine."
99,"normal text here, but not too normal...???","<em>normal text here, but not too normal...???...",http://localhost:3000/test,asap!!! important!!!

Remove HTML tags

In [ ]:
import re
def remove_html(text):
    return re.sub(r'<.*?>', '', text)

In [64]:
df[columns] = df[columns].apply(lambda x: x.apply(remove_html))

In [65]:
df[columns]

,text,html_content,url,abbreviation_text
0,hello world!!!,hello world!!!,https://example.com/test?x=1&y=2,"btw, this is great!!!"
1,this is lowercase-ish...,this is lowercase-ish...,http://www.example.org/page,fyi: check this asap!
2,wow... really???,wow... really???,https://openai.com/,lol!!! idk why :)
3,mixed case text,mixed case text,https://example.com/a/b#section,"imo, it's ok."
4,extra spaces,extra spaces,www.example.com,pls fix this... thx!
...,...,...,...,...
95,this is a test sentence with mixed case....,this is a test sentence with mixed case....btw...,https://www.google.com/search?q=hello%20world,lol... what happened???
96,this is a test sentence with mixed case.!!!???,click here!!!,https://example.com/products/item-42?ref=email...,btw... did you see this?
97,please review this asap... thanks! --,please review this asap... thanks! -- btw...,https://openai.com/research/,til something new!!!
98,"normal text here, but not too normal......","normal text here, but not too normal......",https://www.google.com/search?q=hello%20world,"idk, maybe it's fine."
99,"normal text here, but not too normal...???","normal text here, but not too normal...???",http://localhost:3000/test,asap!!! important!!!

**Remove URLs**

In [68]:
import re

def remove_urls(text):
    return re.sub(r'(https?://|www\.)\S+', '', text)

In [69]:
df[columns] = df[columns].apply(lambda x: x.apply(remove_urls))

In [70]:
df[columns]

,text,html_content,url,abbreviation_text
0,hello world!!!,hello world!!!,,"btw, this is great!!!"
1,this is lowercase-ish...,this is lowercase-ish...,,fyi: check this asap!
2,wow... really???,wow... really???,,lol!!! idk why :)
3,mixed case text,mixed case text,,"imo, it's ok."
4,extra spaces,extra spaces,,pls fix this... thx!
...,...,...,...,...
95,this is a test sentence with mixed case....,this is a test sentence with mixed case....btw...,,lol... what happened???
96,this is a test sentence with mixed case.!!!???,click here!!!,,btw... did you see this?
97,please review this asap... thanks! --,please review this asap... thanks! -- btw...,,til something new!!!
98,"normal text here, but not too normal......","normal text here, but not too normal......",,"idk, maybe it's fine."
99,"normal text here, but not too normal...???","normal text here, but not too normal...???",,asap!!! important!!!

**Remove Punctuation**

In [71]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [72]:
df[columns] = df[columns].apply(lambda x: x.apply(remove_punctuation))

In [73]:
df[columns]

,text,html_content,url,abbreviation_text
0,hello world,hello world,,btw this is great
1,this is lowercaseish,this is lowercaseish,,fyi check this asap
2,wow really,wow really,,lol idk why
3,mixed case text,mixed case text,,imo its ok
4,extra spaces,extra spaces,,pls fix this thx
...,...,...,...,...
95,this is a test sentence with mixed case,this is a test sentence with mixed casebtw,,lol what happened
96,this is a test sentence with mixed case,click here,,btw did you see this
97,please review this asap thanks,please review this asap thanks btw,,til something new
98,normal text here but not too normal,normal text here but not too normal,,idk maybe its fine
99,normal text here but not too normal,normal text here but not too normal,,asap important

**Chat abrevation removal**

In [75]:
abbreviations = {
    "lol": "laughing out loud",
    "lmao": "laughing my ass off",
    "rofl": "rolling on the floor laughing",
    "brb": "be right back",
    "btw": "by the way",
    "idk": "I don't know",
    "idc": "I don't care",
    "imo": "in my opinion",
    "imho": "in my humble opinion",
    "tbh": "to be honest",
    "ngl": "not gonna lie",
    "omg": "oh my god",
    "wtf": "what the fuck",
    "wth": "what the hell",
    "fyi": "for your information",
    "asap": "as soon as possible",
    "irl": "in real life",
    "dm": "direct message",
    "pm": "private message",
    "afk": "away from keyboard",
    "thx": "thanks",
    "ty": "thank you",
    "yw": "you're welcome",
    "np": "no problem",
    "pls": "please",
    "plz": "please",
    "u": "you",
    "ur": "your",
    "r": "are",
    "cuz": "because",
    "bc": "because",
    "b4": "before",
    "2day": "today",
    "2moro": "tomorrow",
    "4": "for",
    "gr8": "great",
    "msg": "message",
    "pic": "picture",
    "ppl": "people",
    "w/": "with",
    "w/o": "without",
}

In [74]:
def replace_abbreviations(text):
    words = text.split()

    for i in range(len(words)):
        if words[i].lower() in abbreviations:
            words[i] = abbreviations[words[i].lower()]

    return " ".join(words)

In [78]:
df[columns] = df[columns].apply(lambda x: x.apply(replace_abbreviations))

In [79]:
df[columns]

,text,html_content,url,abbreviation_text
0,hello world,hello world,,by the way this is great
1,this is lowercaseish,this is lowercaseish,,for your information check this as soon as pos...
2,wow really,wow really,,laughing out loud I don't know why
3,mixed case text,mixed case text,,in my opinion its ok
4,extra spaces,extra spaces,,please fix this thanks
...,...,...,...,...
95,this is a test sentence with mixed case,this is a test sentence with mixed casebtw,,laughing out loud what happened
96,this is a test sentence with mixed case,click here,,by the way did you see this
97,please review this as soon as possible thanks,please review this as soon as possible thanks ...,,til something new
98,normal text here but not too normal,normal text here but not too normal,,I don't know maybe its fine
99,normal text here but not too normal,normal text here but not too normal,,as soon as possible important

**Text correction**

In [80]:
from textblob import TextBlob

In [81]:
def correct_spelling(text):
    return str(TextBlob(text).correct())

In [82]:
df[columns] = df[columns].apply(lambda x: x.apply(correct_spelling))

**Emoji remover**

this example doesn't have emoji

In [83]:
import re

def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport
        "\U0001F700-\U0001F77F"  # alchemical symbols
        "\U0001F900-\U0001F9FF"  # supplemental symbols
        "\U0001FA00-\U0001FAFF"  # extended symbols
        "\U00002700-\U000027BF"  # dingbats
        "\U00002600-\U000026FF"  # miscellaneous symbols
        "]+",
        flags=re.UNICODE
    )

    return emoji_pattern.sub("", text)

In [84]:
df[columns] = df[columns].apply(lambda x: x.apply(remove_emojis))

In [85]:
df[columns]

,text,html_content,url,abbreviation_text
0,hello world,hello world,,by the way this is great
1,this is lowercaseish,this is lowercaseish,,for your information check this as soon as pos...
2,now really,now really,,laughing out loud I don't know why
3,mixed case text,mixed case text,,in my opinion its ok
4,extra spaces,extra spaces,,please fix this thanks
...,...,...,...,...
95,this is a test sentence with mixed case,this is a test sentence with mixed casebtw,,laughing out loud what happened
96,this is a test sentence with mixed case,click here,,by the way did you see this
97,please review this as soon as possible thanks,please review this as soon as possible thanks ...,,til something new
98,normal text here but not too normal,normal text here but not too normal,,I don't know maybe its fine
99,normal text here but not too normal,normal text here but not too normal,,as soon as possible important

Example

In [87]:
txt = "OMG 😍!!! I luvvv this movie sooo much 😂😂. It's awsome!!! Check it out at https://example.com 🚀 #BestMovieEver"

In [88]:
remove_emojis(txt)

"OMG !!! I luvvv this movie sooo much . It's awsome!!! Check it out at https://example.com  #BestMovieEver"

Emoji handling

In [89]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 7.0 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [91]:
import emoji

In [92]:
print(emoji.demojize(txt))

OMG :smiling_face_with_heart-eyes:!!! I luvvv this movie sooo much :face_with_tears_of_joy::face_with_tears_of_joy:. It's awsome!!! Check it out at https://example.com :rocket: #BestMovieEver

**Tokenization**

Word tokenization

In [93]:
df[columns].apply(lambda x: x.apply(lambda y: y.split()))

,text,html_content,url,abbreviation_text
0,"[hello, world]","[hello, world]",[],"[by, the, way, this, is, great]"
1,"[this, is, lowercaseish]","[this, is, lowercaseish]",[],"[for, your, information, check, this, as, soon..."
2,"[now, really]","[now, really]",[],"[laughing, out, loud, I, don't, know, why]"
3,"[mixed, case, text]","[mixed, case, text]",[],"[in, my, opinion, its, ok]"
4,"[extra, spaces]","[extra, spaces]",[],"[please, fix, this, thanks]"
...,...,...,...,...
95,"[this, is, a, test, sentence, with, mixed, case]","[this, is, a, test, sentence, with, mixed, cas...",[],"[laughing, out, loud, what, happened]"
96,"[this, is, a, test, sentence, with, mixed, case]","[click, here]",[],"[by, the, way, did, you, see, this]"
97,"[please, review, this, as, soon, as, possible,...","[please, review, this, as, soon, as, possible,...",[],"[til, something, new]"
98,"[normal, text, here, but, not, too, normal]","[normal, text, here, but, not, too, normal]",[],"[I, don't, know, maybe, its, fine]"
99,"[normal, text, here, but, not, too, normal]","[normal, text, here, but, not, too, normal]",[],"[as, soon, as, possible, important]"

Sentance tokenization

In [94]:
df[columns].apply(lambda x: x.apply(lambda y: y.split('.')))

,text,html_content,url,abbreviation_text
0,[hello world],[hello world],[],[by the way this is great]
1,[this is lowercaseish],[this is lowercaseish],[],[for your information check this as soon as po...
2,[now really],[now really],[],[laughing out loud I don't know why]
3,[mixed case text],[mixed case text],[],[in my opinion its ok]
4,[extra spaces],[extra spaces],[],[please fix this thanks]
...,...,...,...,...
95,[this is a test sentence with mixed case],[this is a test sentence with mixed casebtw],[],[laughing out loud what happened]
96,[this is a test sentence with mixed case],[click here],[],[by the way did you see this]
97,[please review this as soon as possible thanks],[please review this as soon as possible thanks...,[],[til something new]
98,[normal text here but not too normal],[normal text here but not too normal],[],[I don't know maybe its fine]
99,[normal text here but not too normal],[normal text here but not too normal],[],[as soon as possible important]

**NLTK (Tokenization)**

In [95]:
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk

In [96]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [99]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [100]:
Phr = "My name is shaheen"
word_tokenize(Phr)

['My', 'name', 'is', 'shaheen']

In [102]:
Pag = "Hey everyone! My name is Shaheen, and I'm learning NLP. Yesterday, I watched 3 movies, read 2 articles, and spent about 4.5 hours coding in Python. BTW, it was awesome! 😄 I found a great tutorial at https://example.com, and another one at www.learnnlp.com. However, I didn't understand everything, so I asked my friend for help. He replied, LOL, don't worry, you'll get it! Later, I wrote some code, fixed a few bugs, and pushed the project to GitHub. OMG!!! The program finally worked. After that, I ordered pizza, watched YouTube, and went to sleep around 11:30 PM. What a productive day, right?"
sent_tokenize(Pag)

['Hey everyone!',
 "My name is Shaheen, and I'm learning NLP.",
 'Yesterday, I watched 3 movies, read 2 articles, and spent about 4.5 hours coding in Python.',
 'BTW, it was awesome!',
 '😄 I found a great tutorial at https://example.com, and another one at www.learnnlp.com.',
 "However, I didn't understand everything, so I asked my friend for help.",
 "He replied, LOL, don't worry, you'll get it!",
 'Later, I wrote some code, fixed a few bugs, and pushed the project to GitHub.',
 'OMG!!!',
 'The program finally worked.',
 'After that, I ordered pizza, watched YouTube, and went to sleep around 11:30 PM.',
 'What a productive day, right?']

**Stemmer**

In [103]:
from nltk.stem.porter import PorterStemmer

In [104]:
stemmer = PorterStemmer()

def stem_text(text):
    words = text.split()
    stemmed_words = [stemmer.stem(word) for word in words]
    return " ".join(stemmed_words)

In [107]:
exp = 'walk walks walking walked'
stem_text(exp)

'walk walk walk walk walker'

In [108]:
exp2 = "The students were studying machine learning while researchers were developing intelligent systems. They were running experiments, analyzing results, and improving their models. Some people enjoyed reading research papers, while others preferred building applications and testing algorithms. The engineers worked tirelessly, solving problems and creating innovative solutions."

In [109]:
stem_text(exp2)

'the student were studi machin learn while research were develop intellig systems. they were run experiments, analyz results, and improv their models. some peopl enjoy read research papers, while other prefer build applic and test algorithms. the engin work tirelessly, solv problem and creat innov solutions.'

**Lemmatization**

In [110]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()
    lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(lemmatized_words)